### ISSUE TITLE
Linking Error

### ISSUE THREAD

**Issue by yangyushi** [yangyushi/FishPy#7]
I got this issue for a typical dataset,

```python
Traceback (most recent call last):
  File "script/link.py", line 57, in <module>
    blur_velocity=blur
  File "/newhome/yy17363/src/FishPy/fish_track/linking.py", line 792, in relink_by_segments
    relinked_segments += relink(trajs, dx, dt, blur, blur_velocity)
  File "/newhome/yy17363/src/FishPy/fish_track/linking.py", line 719, in relink
    network = np.concatenate((unique_links, best))
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
```

This is likely to be related to a wrong way to handing empty lists.

**Comment by yangyushi** [comment]
fixed by f3adbe0
